### ISSUE TITLE
Weird Table Manifest Annotations Uploading

### ISSUE THREAD

**Issue by brynnz22** [Sage-Bionetworks/schematic#834] opened 2022-07-21 20:25 UTC
**Describe the bug**
When attempting to use the table feature, instead of uploading manifests as Synapse annotations, the table leaves empty metadata values that were included in the csv. When uploading another manifest, it may, or may not, correctly fill in the table. When reuploading the same csv (with missing metadata in the table) it will update the metadata correctly, but also append the same rows onto the table, creating duplicates. It will then cause other empty metadata values for manifests that were originally uploaded correctly. Please see the version history of the table [here](https://www.synapse.org/#!Synapse:syn33342647.3/tables/).

**To Reproduce**
1. Enter the command `schematic model -c /path/to/config.yml submit -mp /path/to/manifest/csv -d syn33340846 -mrt table`
2. See how the manifest is reflected in the corresponding table.
3. Upload another manifest using the same command
4. See how the manifest is reflected in the corresponding table.
5. Upload a third manifest using the same command.
6. See how the manifest is reflected in the corresponding table.

**Expected behavior**
The table will accurately capture all of the metadata reflected in the manifest, leaving no empty values. It will also overwrite existing metadata when re-submitting a manifest (and not append more rows onto the table.). It will not impact other metadata that was originally correctly uploaded.

**Priority** (select one)
- [x ] Critical 🆘

**Screenshots**

**Desktop (if applicable, please complete the following information):**
 - OS: iOS
 - Browser Chrome

**Additional context**
The two attached manifests can be used to testing purposes. The CSBC data model csv can be found [here](https://docs.google.com/spreadsheets/d/1hbG1vdi8a0gc-6psn5VgsBgyMl6IOhDSbHWDuC_8EXo/edit#gid=59750547)
[CA184898.csv](https://github.com/Sage-Bionetworks/schematic/files/9162572/CA184898.csv)
[CA193313.csv](https://github.com/Sage-Bionetworks/schematic/files/9162573/CA193313.csv)

**Comment by mialy-defelice** [comment] 2022-07-21 20:34
@brynnz22 can you give me access to your table?

Naively, I think the problem is, the manifests will all be called the same thing, since they are all referencing the same component (the name is generated from the component name). This will cause synapse to keep adding to the same table on Synapse. Schematic in this case is anticipating that per project you would have one version of each manifest. If you're loading into the same dataset this could also cause overwriting of the manifest that is loaded as a csv. For this we might need to create a new feature to address this unique use case. 

A possible solution would be to add an option to append the users manifest name to the table and csv name. Thus allowing multiple manifests of the same type to be uploaded.

Tagging @ychae for visibility.

**Comment by brynnz22** [comment] 2022-07-21 20:39
@mialy-defelice I added you as an administrator. These manifests would be added to the appropriate projects on synapse, so these two example manifests would technically be uploaded to different projects. We just tried this for testing purposes. So are you saying that we would just need to keep adding onto the same manifest if uploading via Schematic? I think perhaps we would be doing this. I can try adding onto the same manifest and see if this fixes the problem. @vpchung does this seem like the way we would do things in the long run for CSBC?

**Comment by vpchung** [comment] 2022-07-21 20:45
Thank you for the insightful reply, @mialy-defelice !

@brynnz22 yes, I think in the long run, we would (should?) always add and make changes to an existing manifest. I believe that's how the DCA works, in that, the manifest generator would link the user to an existing manifest if it already exists.  Is my understanding correct, @mialy-defelice ?

**Comment by brynnz22** [comment] 2022-07-21 20:55
@mialy-defelice I attempted to just add new rows to the same manifest with a different batch that created [this table](https://www.synapse.org/#!Synapse:syn33344808/tables/), and it is still doing the same thing. So I am thinking that is not the problem?

**Comment by mialy-defelice** [comment] 2022-07-21 22:32
I am getting a little confused on what what is being uploading, what is happening and what is expected. Its always tricky trying to convey this all via text.

I'll summarize what I understand so far:
1. @brynnz22 you are trying to upload several manifests of the same component type (`PublicationView`) as tables (or are possibly okay with adding to the same table) in Synapse.
   1. My expectation would be that for each manifest of the same component type, you would get an addition of information from each manifest to the same table, since tables are given the same name if they come from the same component.
       1. The way to work around this without a new feature would be to upload to different projects.
   2. It looks like schematic is loading the CSV manifests to you dataset folder depending on the name of the manifest you were originally uploading. This means that it is not overwriting any earlier data uploads, but if you upload the same manifest twice, it would overwrite.
   3. The CSV manifests (in the dataset folder) also have annotations attached to them. These annotations are its `etag`, `entityId` and the component the manifest refers to.
2. If you now upload a new type of component (`DatasetView`) to its own dataset you get a new table and a new csv uploaded to the appropriate dataset folder. This csv also has annotations uploaded.

Do you want the manifest csvs combined the same way the tables are combined?
Are you trying to find the best way to combine the manifests in the Table?
I understand you are testing for now, if you don't plan on combining manifests in the table in the future, I would suggest just deleting the test table when you are done with it, or deleting the rows so you can see what it would look like if you were then to upload the next manifest to a new project.

I'm confused by this: 
>I attempted to add new rows to the same manifest with a different batch that created [this table](https://www.synapse.org/#!Synapse:syn33344808/tables/), and it is still doing the same thing. So I am thinking that is not the problem?

**Comment by brynnz22** [comment] 2022-07-21 23:55
@mialy-defelice I am not sure I fully understand what you mean, but I will try to explain:

-  We are fine adding new rows onto the same manifest. We were not sure if it had to be one manifest, or if we could submit a new manifest every time we wanted to add new rows to the table. So I think this was part of the confusion, but we understand that it needs to be the same manifest, which is fine.
- The second comment I made about the [DatasetView table](https://www.synapse.org/#!Synapse:syn33344808/tables/) is that I did use the same manifest and added new rows onto it and I reached the same error (namely that the table was updating weirdly by removing metadata values). As you can see, I submitted one manifest for the DatasetView testing table by looking at [this folder](https://www.synapse.org/#!Synapse:syn33344746). I uploaded the same manifest multiple times, adding new rows each time. As you can see in the [corresponding table](https://www.synapse.org/#!Synapse:syn33344808/tables/), many of the values are missing that do exist in the csv.

I hope this makes sense. This is hard to explain via text. Let me know if you would rather talk really quick.

**Comment by mialy-defelice** [comment] 2022-07-22 17:14
Okay, as far as I can understand,... I think given what you are describing what you are doing, it's actually working as intended. So let's discuss how to do this in a way that gets you what you want.

Feel free to schedule some time with me on my calendar next week!

**Comment by brynnz22** [comment] 2022-07-22 18:16
@mialy-defelice Thanks for meeting with me!

As discussed, I tried another test run using different manifests and not trying to upload the same manifest twice. Unfortunately, the same error is occurring where annotations are missing. Please see the [folder](https://www.synapse.org/#!Synapse:syn33382831) I uploaded the two manifests to, and the [corresponding table](https://www.synapse.org/#!Synapse:syn33382892/tables/). I also [versioned the table](https://www.synapse.org/#!Synapse:syn33382892.2/tables/) after each upload so you can see what happened. I understand that I can combine the manifests for the same projects for now to get our legacy annotations up into their appropriate projects, but this will not be helpful in the long run as we will be constantly adding new metadata for the components (e.g. publications, grants, datasets, tools, etc.), so being able to add new rows using the table feature will be extremely helpful. We are using the table feature instead of the default annotations feature due to the 500 character limit.

Thanks again for all of your help!

**Comment by aclayton555** [comment] 2022-09-07 21:55
This issue to be updated following discussion held with FAIR (meeting notes: https://docs.google.com/document/d/14dFZ5w894-pTVmplLdgR366mHrCvpcrO8lTqI83zyQ0/edit#)

**Comment by brynnz22** [comment] 2022-09-07 21:59
Here is the command I used in the meeting: 

`schematic model -c /Users/bzalmanek/Documents/csbc_schematic/schematic/config.yml submit -mp /Users/bzalmanek/Desktop/FAIRTableMeeting/newManifest/DatasetView.Manifest.1st.csv -d syn35862457 -vc DatasetView -mrt table`

I ussed version Schematicpy version 22.8.1

**Comment by andrewelamb** [comment] 2022-09-13 17:40
@GiaJordan [Replace_table method in schematic_db](https://github.com/Sage-Bionetworks/schematic_db/blob/develop/synapse/synapse.py#L241)

**Comment by lopierra** [comment] 2022-09-14 23:13
I am having a similar issue with INCLUDE, using the Data Curator app. I see you are already working on it, but please let me know if I should file a separate issue to document the problem. Thanks!

**Comment by GiaJordan** [comment] 2022-09-15 16:38
@lopierra Thanks for the update! Could you please open up another issue with your specific details and mention this issue in one of your comments so that I can cross reference the two?
Thanks so much!

**Comment by GiaJordan** [comment] 2022-09-19 18:34
So after reviewing this thread and the notes from the previous conversation, it seems there are two issues occurring:
(also, all synapse links commented before the google doc with the meeting notes are now dead and inaccessible)
1. When a manifest is uploaded, and then is reuploaded, rows already uploaded to the table are duplicated, and this is not desired. Preferred behavior is only new rows are added, and old rows are not duplicated.
In this scenario, new metadata will be added onto an existing manifest before upload, and information will be stored in a single table per datatype.

2. When one manifest is uploaded to a given dataset, and then is no longer needed, and another manifest is uploaded to the same dataset with the intention of replacing it, rows from the first dataset persist in the table after the second upload, and this is not desired. Preferred behavior is to remove all rows from the existing table, and replace with only the rows from the new manifest.
In this scenario, only one manifest per datatype will be present in each project, and new information will be added onto the single manifest as appropriate. If multiple manifests exist for a given datatype, they will be separated into different projects so that only one exists within each project.

@brynnz22 @vpchung is this correct?

**Comment by brynnz22** [comment] 2022-09-19 19:06
Hi @GiaJordan. #1 is correct. Based on our workshop meeting with Milen #2 is the correct behavior the FAIR team expects when different manifests are uploaded. @milen-sage indicated that priority should be fixing the table feature so it behaves exactly as you described in your second point. However, this is related to a feature that MC2 would like. Because we upload manifests monthly based on a publication crawling script, we will be using different manifests every month and we would like the rows to be appended onto the existing table and a second manifest added to the corresponding folder (instead of replacing the existing manifest and only having one manifest). I am not sure how your team wants to prioritize/organize this?

**Comment by lopierra** [comment] 2022-09-19 19:22
Just FYI, the INCLUDE issue (#911) is slightly different - we want to upload multiple manifests (one per cohort) per datatype and have them be concatenated. I'm wondering now if that might not be possible if the desired behavior is to be able to update & replace manifests.

**Comment by GiaJordan** [comment] 2022-09-19 19:49
@lopierra  Yes! noted, The two issues seemed related but with some key differences, and I was trying to specify exactly what the differences were so I could create sets of acceptance criteria appropriate for each.

**Comment by GiaJordan** [comment] 2022-09-21 17:33
Development has been ongoing but to better organize all of the Asks and their respective priorities, I'm converting this and other related tickets to Epic status, cc @milen-sage. Development for all related table upload bugs and feature requests can be followed under the [Table Behavior](https://github.com/Sage-Bionetworks/schematic/milestone/31) github milestone.

This specific asks of this ticket will be tracked in the two following issues:

- #914 Ghost Table Upload Behavior
- #835 Feature to allow table updates
with #914 being higher priority

**Comment by GiaJordan** [comment] 2022-09-21 17:53
Closing this issue, tracking will continue on each specific ticket as appropriate

**Closed by GiaJordan** 2022-09-21 17:53 UTC
Labels: bug

**Comment by milen-sage** [comment] 2022-09-23 14:57
Thanks for the note @lopierra! #835 has been prioritized as well.
