### ISSUE TITLE
--use_annotations flag for manifest get is broken in develop

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/schematic#507] opened 2021-07-28 17:23 UTC
**Describe the bug**
The --use_annotations flag for `manifest get` works in the current pip 1.0.0 release but is not working when I install `develop`.  Discovered while testing #479.

**To Reproduce**
pip uninstall schematicpy
pip install git+git://github.com/Sage-Bionetworks/schematic.git@develop  
schematic manifest --config config.yml get --title filename_test -dt GenomicsAssay --jsonld NF.jsonld --dataset_id syn24611057 --sheet_url --use_annotations --oauth

Will get all the way to `Permission Id: anyoneWithLink` and then spit out an error - see below. 

**Expected behavior**
I expected this function to provide a google link. 

**Screenshots**
```
(bgrande-issue-476) ➜  schematic-upstream git:(develop) ✗ pip uninstall schematicpy
...
  Successfully uninstalled schematicpy-1.0.0
(bgrande-issue-476) ➜  schematic-upstream git:(develop) ✗ pip install git+git://github.com/Sage-Bionetworks/schematic.git@develop                                 
...
Successfully installed schematicpy-1.0.0 synapseclient-2.3.1
(bgrande-issue-476) ➜  schematic-upstream git:(develop) ✗ schematic manifest --config config.yml get --title filename_test -dt GenomicsAssay --jsonld NF.jsonld --dataset_id syn24611057 --sheet_url --use_annotations --oauth
Starting schematic...
The (model > input > validation_schema) argument with value 'data/validation_schemas/example_validation_schema.json' is being read from the config file.
The '--json_schema' argument is being taken from configuration file (model > input > validation_schema), i.e., 'data/validation_schemas/example_validation_schema.json'.
warning: The `use_annotations` option is currently only supported when there is no manifest file for the dataset in question.

UPGRADE AVAILABLE

A more recent version of the Synapse Client (2.4.0) is available. Your version (2.3.1) can be upgraded by typing:
    pip install --upgrade synapseclient

Python Synapse Client version 2.4.0 release notes

https://python-docs.synapse.org/build/html/news.html

 [####################]100.00%   1/1   Done...
Downloading  [####################]100.00%   19.4MB/19.4MB (2.3MB/s) SYNAPSE_TABLE_QUERY_79735899.csv.synapse_download_79735899 Done...
    [WARNING] /opt/miniconda3/envs/bgrande-issue-476/lib/python3.9/site-packages/synapseclient/table.py:1921: DtypeWarning: Columns (7,20,21,27,34,37,38,41,42,44,45,46,49,50,51) have mixed types.Specify dtype option on import or set low_memory=False.
  return _csv_to_pandas_df(self.filepath,

warning: /opt/miniconda3/envs/bgrande-issue-476/lib/python3.9/site-packages/synapseclient/table.py:1921: DtypeWarning: Columns (7,20,21,27,34,37,38,41,42,44,45,46,49,50,51) have mixed types.Specify dtype option on import or set low_memory=False.
warning:   return _csv_to_pandas_df(self.filepath,
Using slower (non-batch) sequential mode
JSON schema successfully generated from schema.org schema!
JSON schema file log stored as data/json_schema_logs/json_schema_log.json
Permission Id: anyoneWithLink
Traceback (most recent call last):
  File "/opt/miniconda3/envs/bgrande-issue-476/bin/schematic", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/bgrande-issue-476/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/envs/bgrande-issue-476/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/envs/bgrande-issue-476/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/envs/bgrande-issue-476/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/envs/bgrande-issue-476/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/envs/bgrande-issue-476/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/miniconda3/envs/bgrande-issue-476/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/opt/miniconda3/envs/bgrande-issue-476/lib/python3.9/site-packages/schematic/manifest/commands.py", line 135, in get_manifest
    result = manifest_generator.get_manifest(
  File "/opt/miniconda3/envs/bgrande-issue-476/lib/python3.9/site-packages/schematic/manifest/generator.py", line 974, in get_manifest
    manifest_url, manifest_df = self.get_manifest_with_annotations(annotations)
  File "/opt/miniconda3/envs/bgrande-issue-476/lib/python3.9/site-packages/schematic/manifest/generator.py", line 907, in get_manifest_with_annotations
    manifest_sh = self.set_dataframe_by_url(manifest_url, manifest_df)
  File "/opt/miniconda3/envs/bgrande-issue-476/lib/python3.9/site-packages/schematic/manifest/generator.py", line 814, in set_dataframe_by_url
    wb.set_data_validation(start = start_col, end = end_col, condition_type = None)
  File "/opt/miniconda3/envs/bgrande-issue-476/lib/python3.9/site-packages/pygsheets/utils.py", line 163, in wrapper
    return func(*args, **kwargs)
  File "/opt/miniconda3/envs/bgrande-issue-476/lib/python3.9/site-packages/pygsheets/worksheet.py", line 1624, in set_data_validation
    grange = GridRange(worksheet=self, start=start, end=end)
  File "/opt/miniconda3/envs/bgrande-issue-476/lib/python3.9/site-packages/pygsheets/address.py", line 245, in __init__
    self._apply_index_constraints()
  File "/opt/miniconda3/envs/bgrande-issue-476/lib/python3.9/site-packages/pygsheets/address.py", line 417, in _apply_index_constraints
    assert self._start[1] <= self._end[1]
AssertionError
```

**Comment by BrunoGrandePhD** [comment] 2021-07-28 17:45
I see `set_dataframe_by_url()` in the stack trace, so I wonder if @milen-sage's recent change in #496 is the root cause. That should make it easy to debug.

**Comment by milen-sage** [comment] 2021-07-28 18:00
@BrunoGrandePhD  that's what I thought, too. Will take a look to see if I can reproduce on my end.

**Comment by allaway** [comment] 2021-07-28 23:34
This should be resolved by merging https://github.com/Sage-Bionetworks/schematic/commit/75e54b05205d1150e1dd4033d6f8edf3e5c7b183 into `develop`.

**Comment by BrunoGrandePhD** [comment] 2021-07-29 20:39
I think this has been resolved by https://github.com/Sage-Bionetworks/schematic/commit/75e54b05205d1150e1dd4033d6f8edf3e5c7b183 and #508.

**Closed by BrunoGrandePhD** 2021-07-29 20:39 UTC
Labels: bug
