### ISSUE TITLE
HTAN SD: Missing BU demographics records

### ISSUE THREAD

**Issue by MiekoHash** [Sage-Bionetworks/schematic#1165] opened 2023-02-23 23:16 UTC
https://sagebionetworks.jira.com/browse/FDS-33?focusedCommentId=165659

**Comment by milen-sage** [comment] 2023-03-06 20:41
We'll be on the lookout for similar issues, but can't reproduce and closing for now.

**Closed by milen-sage** 2023-03-06 20:41 UTC
