### ISSUE TITLE
Convert entities to tables for HTAN

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/schematic#861] opened 2022-08-10 21:12 UTC
**Is your feature request related to a problem? Please describe.**
The entities in HTAN are ready to be migrated over to the new tables feature

**Describe the solution you'd like**
Migrate the entities in HTAN over to tables

**Comment by milen-sage** [comment] 2022-08-30 17:59
@milen-sage to link script moving entities from HTAN projects to an archive project; and links to the archive project.

**Comment by GiaJordan** [comment] 2022-09-01 16:43
Taking over this ticket in Mialy's absence; I have a few questions just to get caught up. Thanks for your patience.

1. The issue seemed to be limited to some files that were missing. From what I've read I understand that all of the 'missing' files have been reinstated, and we just want to prevent something similar from happening again. Is that correct?
2. The missing files seemed to be limited to the Vanderbilt center, is anyone aware of any other centers that have been migrated successfully and this was an outlier, or was this just the first center to be migrated? If others had been run successfully, has anyone noticed anything special about the Vanderbilt center files that might be related to why they were also migrated?
3. From looking through the `HTAN Vanderbilt` project, it appears the tables are being generated as desired and the problem is just limited to the selection of which entities should be moved. Is that correct?

@aclayton555 @adamjtaylor @vthorsson

**Comment by adamjtaylor** [comment] 2022-09-01 16:46
Thanks @GiaJordan 

1. Yes the files have been reinstated. We need to diagnose why the files were dragged over to the HTAN Archive project along with the indented folder entities and prevent this from happening again.
2. Vanderbilt was the only "production"  HTAN center for which the migration had been applied.
3. Yes, think this is only an issue with entity movement. The incorrectly moved files don't seem to show up in the tables.

**Comment by GiaJordan** [comment] 2022-09-01 16:53
@adamjtaylor perfect, thanks for the info!

**Comment by GiaJordan** [comment] 2022-09-06 17:28
Updates:
The erroneously moved entities were moved because they were batch uploaded with a manifest instead of being uploaded one at at a time through the synapse web portal. 
I'm currently working to update the logic to differentiate between files uploaded with a manifest and entities created by a manifest to store annotations. So far I've also added a command so that the migration can be run easily in the future, and developed and included functionality to move archived entities back to their original folders in case it's necessary again going forward.
@adamjtaylor 
**cc:** @milen-sage @aclayton555 @vthorsson

**Comment by GiaJordan** [comment] 2022-09-06 21:28
Updates:
The files were moved because they were included in a manifest, and the code was structured in a way that assumed every entity within a dataset manifest was a folder entity to hold annotations; this has now been rectified.
I've also included a command to migrate entities to a different project for archival, or to move archived entities back to their original folders in case that use case arises again in the future, along with re-uploading manifests as tables. 
Before merging, I'd like to also do some work on managing how the archival project is structured to avoid running into the folder limits synapse imposes on the main project directory.
@adamjtaylor 
**cc:** @milen-sage @aclayton555 @vthorsson

**Comment by GiaJordan** [comment] 2022-09-07 22:16
Development is largely finished for this issue and testing wrt entity migration has been completed in sandbox projects.
We're ready now to do dry runs with HTAN before moving this into production. I'll be in touch shortly @adamjtaylor to discuss next steps and to coordinate testing.
**CC:** @milen-sage

**Comment by GiaJordan** [comment] 2022-09-09 18:54
@milen-sage meeting to test scheduled. Development tentatively finished, but will leave marked as "in progress" until testing is complete and it's ready to merge

**Closed** 2022-09-13 20:10 UTC
Labels: feature

**Comment by milen-sage** [comment] 2022-09-13 21:35
@aclayton555 

@GiaJordan and @adamjtaylor met and tested the script moving entities from existing HTAN projects, using HTAN Center A. The script worked as expected. Based on @adamjtaylor's request @GiaJordan will hand over the script to @elv-sb to run and move the entities across centers' projects; this will happen later this week when @elv-sb is back in office. @elv-sb could you reach out to  @GiaJordan when you are back if you have any questions around running the script.

**Comment by aclayton555** [comment] 2022-09-13 22:39
Thank you all! Including @abbywall here for awareness as we are working to determine the timing of next steps to make sure it aligns across teams.
