### ISSUE TITLE
Data disappears from Synapse Table when manifest submitted through DCA

### ISSUE THREAD

**Issue by lopierra** [Sage-Bionetworks/schematic#911] opened 2022-09-16 00:01 UTC
**Describe the bug**
I have an INCLUDE project with 3 folders for 3 different cohorts. I attempted to use the INCLUDE Data Curator App to upload a Study metadata manifest in each folder (all named synapse_storage_manifest_study.csv) and then be able to see the 3 manifests combined in a single Table. 

The Table is automatically created and looks correct when I validate & submit the first manifest, but when I submit subsequent manifests, the StudyName field for the previous manifests disappears from the Table and is only kept for the latest manifest. The CSV files for the manifests all have the correct values.

(Not sure if this is relevant, but StudyName is the only required field that is a string - the other two required fields (StudyCode and Program) are enums, and dbGaP is optional & blank.)

**To Reproduce**
1. Create [Synapse Project](https://www.synapse.org/#!Synapse:syn31538613/files/) with 3 folders for 3 different cohorts  ([ABCDS](https://www.synapse.org/#!Synapse:syn36358145), [DSC](https://www.synapse.org/#!Synapse:syn36358756), and [BRI-DSR](https://www.synapse.org/#!Synapse:syn31538629)) [I added @GiaJordan to the team, but please let me know if someone else needs access]
2. Use [INCLUDE Data Curator App](https://www.synapse.org/#!Synapse:syn30109400) to validate & submit a Study manifest to each folder
3. Manifests will be correct in CSV form ([ABCDS](https://www.synapse.org/#!Synapse:syn36358705), [DSC](https://www.synapse.org/#!Synapse:syn36358959), [BRI-DSR](https://www.synapse.org/#!Synapse:syn36358405))
4. StudyName values disappear from the common Table ([study_synapse_storage_manifest_table](https://www.synapse.org/#!Synapse:syn36358372/tables/)) for all but the most recently submitted manifest

**Expected behavior**
A new row with all values present should be added to the Table after each manifest is submitted.

**Priority** (select one)
- [ ] Minor ⬇️
- [ ] Major 📢
- [X] Critical 🆘

**Screenshots**
![image](https://user-images.githubusercontent.com/34149564/190528758-793b72be-cc6c-4e57-8e86-7e66c40529d0.png)

Manifests were submitted in this order: BRI-DSR, DSC, ABC-DS. Each time, StudyName only appears for the most recently submitted manifest, and disappears from the previous rows.

The two rows of dashes occurred when I tried re-uploading the first manifest (BRI-DSR), but it replaced both of the previous rows with dashes instead of only replacing the BRI-DSR row. Not sure if this is an expected behaviour.

**Desktop (if applicable, please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
Similar to #834

**Comment by GiaJordan** [comment] 2022-09-16 17:33
Thank you @lopierra for capturing this in a ticket! I believe it's the same underlying behavior causing this and the other mentioned issue. For now, I don't think anyone else will need access and I have enough information to start as I work on the other issue and this one. Thanks again!

**Comment by GiaJordan** [comment] 2022-09-21 17:47
Breaking up into two parts:
Bug encountered will be tracked in #914 ,
Feature request is duplicate of #835 and will be tracked there

**Comment by GiaJordan** [comment] 2022-09-21 17:53
Closing this issue, tracking will continue on each specific ticket as appropriate

**Closed by GiaJordan** 2022-09-21 17:53 UTC
Labels: bug
