### ISSUE TITLE
Pre-populate manifest template with existing Synapse annotations (only applies if manifest is missing)

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/schematic#312] opened 2020-10-14 20:58 UTC
I think that populating the manifest with annotations that exist on the files already (for keys that are in the manifest, and for valid values) could be useful in a few use cases: 

1) user is annotating old files that may have partial/noncompliant annotations (this is our biggest use case at present)
2) user inadvertently annotates files via a different mechanism with some annotations such as syncToSynapse
3) user programmatically annotates data and wants to do final touch up/validation/manual annotation in app
4) schema changes in the future, and user or data curator wants to update annotations to make compliant with schema changes

**Comment by BrunoGrandePhD** [comment] 2020-11-09 21:50
> user is annotating old files that may have partial/noncompliant annotations (this is our biggest use case at present)

Given that this is the biggest use case at the moment, the first version of this feature could exist as a toggle—as @allaway suggested—that would cause `schematic` to build a "draft manifest" from all annotations of the corresponding files rather than considering any existing CSV manifest in the folder in question. 

At the implementation level, this "draft manifest" would be exported to a CSV file and re-imported using `manifest.generator.populate_manifest_spreadsheet()` as if it was the CSV manifest from the root of the folder. The function that would pull the annotations from Synapse could be stored in a file alongside the `synapse/store.py` submodule (e.g._ `synapse/get.py` or `synapse/retrieve.py`). The JSON-LD schema would be used to map the Synapse annotation key names (`@id`) to the display name that usually appears in the CSV manifest (`sms:displayName`). 

Outstanding questions:

- If there a value exists for a given file in both the existing CSV manifest and Synapse annotation, which one should take precedence? While this conflict resolution might not be included in the first version of this feature, I'm curious to know to what others would expect. 
- Should we subset the columns in the "draft manifest" to those appearing in the schema? Based on a quick test, it appears that additional columns aren't flagged as invalid, but they're silently dropped when uploaded to Synapse. 

@milen-sage: Thoughts?

**Comment by milen-sage** [comment] 2020-11-10 21:23
> > user is annotating old files that may have partial/noncompliant annotations (this is our biggest use case at present)
> 
> Given that this is the biggest use case at the moment, the first version of this feature could exist as a toggle—as @allaway suggested—that would cause `schematic` to build a "draft manifest" from all annotations of the corresponding files rather than considering any existing CSV manifest in the folder in question.

Yes - that's a neat idea! Assuming the toggle would be reflected in the the corresponding CLI/API calls (e.g. the modules you suggest below) as well

> 
> At the implementation level, this "draft manifest" would be exported to a CSV file and re-imported using `manifest.generator.populate_manifest_spreadsheet()` as if it was the CSV manifest from the root of the folder. The function that would pull the annotations from Synapse could be stored in a file alongside the `synapse/store.py` submodule (e.g._ `synapse/get.py` or `synapse/retrieve.py`). The JSON-LD schema would be used to map the Synapse annotation key names (`@id`) to the display name that usually appears in the CSV manifest (`sms:displayName`).
> 

The overall plan^ sound good - but let's discuss implementation: how do we want to structure the synapse store.py and the get/retrieve functionality. I've been thinking that we might want to refactor a bit (not too much :) ) the synapse/store.py module and this might be a good time to do that. We can sync up on that tomorrow.

> Outstanding questions:
> 
> * If there a value exists for a given file in both the existing CSV manifest and Synapse annotation, which one should take precedence? While this conflict resolution might not be included in the first version of this feature, I'm curious to know to what others would expect.

Good point - since annotations can be set via csv and the synapse annotations UI, I think we ideally would give precedence to the latest-change event. Synapse keeps track of when the csv file was modified; @BrunoGrandePhD could you check if Synapse keeps track of when annotations are modified? My cursory check indicates that changes to Synapse entity annotations update the 'Date Modified' property on the entity; however there are many actions aside from changing annotations that update the entity's 'Date Modified', so that may not be reliable timestamp for our purposes? If we can't decide based on timestamps in Synapse, I have a slight preference for assuming the csv is the source of truth - mainly because Synapse versions the csv file; Synapse doesn't version annotations, at present. Also, the manifest csv is interface for annotations update from schematic's user point of view.

> * Should we subset the columns in the "draft manifest" to those appearing in the schema? Based on a quick test, it appears that additional columns aren't flagged as invalid, but they're silently dropped when uploaded to Synapse.

That's another good point... I think we'd like to give the user the opportunity to reuse the annotations they entered even if their annotation keys don't correspond to the schema - e.g. they could change column names to match the schema or delete columns when needed themselves. Perhaps we can make this a toggle as well: i.e. fetch additional columns vs. drop columns outside schema. Eventually, we could also be able to translate some of the existing annotation keys to corresponding schema names, utilizing data model translation/map (#164).  

>   * **Edit:** On second thought, it would make more sense to include the column in case the annotation keys don't exactly match the schema field names. This way, the user can just rename the column in the manifest template to map the existing values (under a different name) to the correct field in the schema for validation.

:) I typed my reply above before reading your edit - exactly the idea.

> @milen-sage: Thoughts?

**Comment by BrunoGrandePhD** [comment] 2020-11-12 00:54
Based on our discussion during the code review today, I think we settled on having an argument to determine the expected behavior if there are conflicts between the Synapse annotations and the CSV manifest file. (We're ignoring the Synapse table for now because sanity.) I propose four different "modes" that could be exposed as a dropdown menu in the front-end:

- Warn about conflicts between CSV manifest and Synapse annotations
    - If the code for pulling Synapse annotations is fast enough, I was thinking of making this behavior the default
- Ignore conflicts between CSV manifest and Synapse annotations
    - In this mode, `schematic` wouldn't even bother loading the Synapse annotations
    - This would be the default if pulling the Synapse annotations is relatively slow
- Give precedence to CSV manifest over the Synapse annotations in case of conflicts
- Give precedence to Synapse annotations over the CSV manifest in case of conflicts

Unless I hear otherwise, I think we should just pull in all annotations, even those that don't appear in the data model, in case different names are used for the same concept (_e.g._ `patient` as the Synapse annotation key  and `patientId` as the JSON-LD data model label). 

@allaway: Does it sound like this approach would cover all of your use cases?

**Comment by BrunoGrandePhD** [comment] 2020-12-02 20:00
Friendly bump for @allaway.

**Note to self:** Update that the code that updates Synapse annotations such that it can guarantee (as much as it can) that the annotations are in sync with the manifest CSV file. In other words, if any errors comes up during the process of updating annotations (_e.g._ because a attribute name isn't a valid annotation key on Synapse), update the annotations using the previous manifest and report an error to the user.

**Comment by allaway** [comment] 2020-12-03 02:43
Sorry for the delay, I was slammed the past couple of weeks!
Thanks for the ping. 

I agree with your proposal. I think this would cover all of the use cases.  

I think " I think we should just pull in all annotations, even those that don't appear in the data model, in case different names are used for the same concept (e.g. patient as the Synapse annotation key and patientId as the JSON-LD data model label)." is a particularly smart move, because there will surely be folks that have annotated data without reading the docs, and we want to make sure that they can correct their annotations as easily as possible (including correcting different names for the same concept). 

One other thought: how will this handle changing etags? My expectation would be that a concurrency error is thrown, rather than "forcing" the change (ie. always retrieving the latest etag and assigning annotations using those). However, the user will probably need to be informed of the concurrency error (and maybe even provided a csv of the subset of rows that had this error? keeping track of concurrency errors is a pain in the synapse web UI at the moment as it just pops up in a dialog box)

**Comment by allaway** [comment] 2020-12-03 02:44
>Warn about conflicts between CSV manifest and Synapse annotations
>    If the code for pulling Synapse annotations is fast enough, I was thinking of making this behavior the default

>Ignore conflicts between CSV manifest and Synapse annotations
>   In this mode, schematic wouldn't even bother loading the Synapse annotations

I agree with making the first behavior the default if possible. In the second option (just overwrite Synapse annotations), I could see there being some potential issues with concurrency as discussed in my previous comment.

**Comment by BrunoGrandePhD** [comment] 2020-12-04 01:30
> Sorry for the delay, I was slammed the past couple of weeks!

No worries! 

> One other thought: how will this handle changing etags? My expectation would be that a concurrency error is thrown, rather than "forcing" the change (ie. always retrieving the latest etag and assigning annotations using those). However, the user will probably need to be informed of the concurrency error (and maybe even provided a csv of the subset of rows that had this error? keeping track of concurrency errors is a pain in the synapse web UI at the moment as it just pops up in a dialog box)

I didn't know what the ETags were for until I looked it up just now. I had been conveniently ignoring them. 😅 
Thanks for bringing them to my attention! 

So, based on my little bit of testing, each entity (_e.g._ file, folder, project) is given an ETag, which is updated every time the contents or the annotations of the entity are changed. This ensures that if two changes are made at the same time, the second attempt is made aware that the entity has changed since being retrieved from Synapse and will force that user to update their local "copy" of the entity before updating the remote "copy". Let me know if I missed anything or if there's anything peculiar about Synapse's implementation of ETags that I should be aware of. 

@allaway: Just to be sure I follow your concern regarding concurrency, are you saying that `schematic` should get the ETags when it pulls the annotations from Synapse to pre-populate the manifest template and then compare them with the latest ETags on Synapse during submission in case the entity has changed in the interim? And if a mismatch occurs, `schematic` (and thus the Data Curator App) should (1) not update anything for any affected entities, and (2) inform the user of the concurrency issue. Did I get that right? 

From what I can tell, there's no way to tell what prompted the new ETag, _i.e._ updated contents or updated annotations. Otherwise, we could proceed with updating the annotations if only the contents were changed. We already store the entity ID in the manifest, so we should be able to store the ETag to prevent conflicts. I agree that the Data Curator app should at least return the entity IDs that had a conflict, but it would be even better if the annotations were inspected for any changes. That said, I can't think of any way to cache the annotations at the time of retrieval so we can compare them with the annotations at the time of submission.

**Comment by milen-sage** [comment] 2020-12-04 02:07
Oh the joys of etags!
Especially in table updates.

afaik, Synapse should handle "locking" of each entity whose annotations are changed, if entities are changed one by one.

A potential problem could arise (thank you @allaway for spotting that) if multiple entities are updated one by one on schematic's side (after a request by the Data Curator App): by the time schematic requests update of entity 10's annotation a user might change the annotations of entity 1 through Synapse. One way to go around this may be to use [syncToSynapse](https://python-docs.synapse.org/build/html/synapseutils.html#synapseutils.sync.syncToSynapse). Also see bulk update annotations via fileviews https://docs.synapse.org/articles/views.html

@BrunoGrandePhD this is something that can be changed [here](https://github.com/Sage-Bionetworks/schematic/blob/7ada70d41df60e0d54d76503d63233ea2eb3068b/schematic/synapse/store.py#L451) (i.e. switching from per entity annotations update to bulk update of all entities)?

That way Synapse will take care of required locks to avoid concurrency issues.

**Comment by allaway** [comment] 2020-12-04 03:08
Milen's comment more or less mirrors what I was thinking, though there's
one other scenario that I was considering that could be problematic:

>Ignore conflicts between CSV manifest and Synapse annotations
>
>In this mode, schematic wouldn't even bother loading the Synapse
annotations
>This would be the default if pulling the Synapse annotations is relatively
slow

My read of this is that schematic would apply annotations regardless of
whether the etag had changed in the interim. So I guess I was envisioning
the following scenario:

December 3 - person a generates a manifest and goes home for the day
December 4 - they fill in the manifest but do not upload it
December 5 - some ambitious postdoc changes some annotations on synapse
December 7 - person a uploads their manifest via the app and it forces an
upload (e.g. ignoring the newly updated etag)

Maybe I misunderstood what the mode was, but based on my interpretation
this would be circumventing the concurrency system on synapse, so the
concurrency issue would never be realized.

Cheers,
Robert

**Comment by milen-sage** [comment] 2020-12-04 16:51
>So I guess I was envisioning the following scenario: December 3 - person a generates a manifest and goes home for the day December 4 - they fill in the manifest but do not upload it December 5 - some ambitious postdoc changes some annotations on synapse December 7 - person a uploads their manifest via the app and it forces an upload (e.g. ignoring the newly updated etag)

Yes, this is a scenario that could happen (don't even need the ambitious postdoc in the picture; it could be the same person that goes home for the day and then changes the annotations on Synapse, but three days later uploads the manifest via the schematic app :)

When we were thinking about it for HTAN (and in general regarding using different interfaces to update metadata), we decided that we have an SOP that lists the supported ways to add and update metadata (i.e. via the data curator app or programmatically via schematic) and 
1) we warn contributors that using any other interface (e.g. directly Synapse) is risky and has caveats (e.g. no versioning of annotations; work can be lost due to overwrites).
2) we warn contributors that any person with edit rights on their team can submit and overwrite metadata, however 
-- all metadata submitted via data curator app/schematic is versioned (i.e. each manifest is versioned on Synapse) so even unintended overwrites happen we can restore the metadata that users request (in addition, we have the google sheets that users generate which have version history, so even if people haven't submitted metadata yet they could workout among themselves what version to submit)

I think 1) is reasonable; risks in 2) can be alleviated even more; e.g. have a data curator app service account; have the data curator app temporarily change perms on fileviews/files for which a sheet has been generated but not uploaded yet, so that no one else but the data curator app user has rights to change files; unlock the files and restore perms when the metadata submission has finished. We decided going the extra implementation length is lower priority given we keep track of versioning and can troubleshoot if overwrites happen if users follow the SOP (which right now we are de-HTAN-ifying, so its reusable.

If assumptions in 2) are still reasonable, I think switching to bulk read/update of annotations would resolve other concurrency concerns, and we can worry about alleviating risks in 2) later? Would that make sense wrt what you envision @allaway?

**Comment by BrunoGrandePhD** [comment] 2020-12-04 23:33
Based on my discussion with @milen-sage from earlier today, I looked into the behavior of file views and their row-wise ETags. Unfortunately, the `ROW_ETAG` value is simply the `etag` of the given file/folder. Updating the annotation of a file caused both the `ROW_ETAG` and `etag` values to change (and remain the same). Hence, we cannot rely on `ROW_ETAG` as a way to specifically detect changes to the annotations (and not the file contents). 

```
❯ synapse query "SELECT * FROM syn23595117" 2> /dev/null | csvcut -t -c 3,8 | csvlook
| ROW_ETAG                             | etag                                 |
| ------------------------------------ | ------------------------------------ |
| 2fd92eb5-e153-4797-a3f7-fb646b1e5f9e | 2fd92eb5-e153-4797-a3f7-fb646b1e5f9e |
| 861807d7-c834-4b95-bab5-62167e424731 | 861807d7-c834-4b95-bab5-62167e424731 |
| c9c24116-31e3-4cd7-88d7-a58b2d6060e2 | c9c24116-31e3-4cd7-88d7-a58b2d6060e2 |
| efbf9148-4eea-4086-ad28-64519d3c3204 | efbf9148-4eea-4086-ad28-64519d3c3204 |
```

**Comment by BrunoGrandePhD** [comment] 2020-12-04 23:50
I also wanted to confirm what @milen-sage said regarding the file view schema: new annotations on a file included in a file view doesn't automatically cause the file view to include the new annotations as columns. 😞 You can edit the file view schema and click "All All Annotations" to add new annotation columns. Fortunately, this can be done programmatically by using `addAnnotationColumns=True` (the default) in `EntityViewSchema()`, although I don't know if this can be used for an existing file view. ¯\_(ツ)_/¯

**Comment by allaway** [comment] 2020-12-04 23:56
Hey both, would you be willing to meet sometime next week to discuss this
further? I think we're saying the same thing, but I just want to make sure
and think we could probably discuss more clearly over a call :)

I would expect the etags to update whether the file was changed or just the
annotations (as you note above) - I just wanted to make sure that the
implementation of things on the `schematic` side considers this system in
its development. Right now, the manifests (when generated) do not include
file etags, so there's no way for schematic to know or to track whether
file annotations are changing unexpectedly between manifest generation and
at the time of applying new annotations.

**Comment by allaway** [comment] 2020-12-04 23:58
"I also wanted to confirm what @milen-sage <https://github.com/milen-sage>
said regarding the file view schema: new annotations on a file included in
a file view doesn't automatically cause the file view to include the new
annotations as columns. 😞 You can edit the file view schema and click "All
All Annotations" to add new annotation columns. Fortunately, this can be
done programmatically by using addAnnotationColumns=True (the default) in
EntityViewSchema(), although I don't know if this can be used for an
existing file view. ¯_(ツ)_/¯"

Yep...fileview schemas are independent of annotation schemas. At least for
now and the foreseeable future :)

**Comment by BrunoGrandePhD** [comment] 2020-12-07 20:45
**Note to self:** Handle deleted files.

**Comment by allaway** [comment] 2022-02-07 16:39
I am reviewing issues, and IMO this was completed a while ago. I see @BrunoGrandePhD  added a note to self at the end, so maybe that's why this is still open?

**Comment by BrunoGrandePhD** [comment] 2022-02-07 20:18
I think we had left this open because we only import annotations if there is no manifest associated with the selected dataset. If a manifest exists, we ignore the annotations regardless of `use_annotations`. 

I've updated the title accordingly to:
> Pre-populate manifest template with existing Synapse annotations (only applies if manifest is missing)

To avoid having this issue live on forever, we can close this issue and open a more specific request for covering the case when a manifests already exists (which requires handling merge conflicts).

**Closed by BrunoGrandePhD** 2022-02-07 20:18 UTC
Labels: feature

**Comment by BrunoGrandePhD** [comment] 2022-02-07 20:27
Here's the issue I created to track the balance of the work alluded in the original issue here:

https://github.com/Sage-Bionetworks/schematic/issues/572

**Comment by allaway** [comment] 2022-02-07 22:36
Ahh, got it, that makes sense. So there could be a discrepancy if someone were to modify an annotation, but not thru the app. Thanks!

**Comment by milen-sage** [comment] 2022-02-07 23:11
Thanks @BrunoGrandePhD  and @allaway for hashing this out! It's very timely since we are introducing a process around triaging issues w/in a 2-week sprint framework and are working on updating the state of our FAIR data issue backlog.
